Introductory/Models/ComplainStatusTrackInfo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Introductory.Models
{
    public class ComplainStatusTrackInfo
    {

        [Key]
        public int ComplainStatusTrackInfoID { get; set; }
        public int ComplainID { get; set; }
        public int ComplainStatusID { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }

        [ForeignKey("ComplainID")]
        public virtual Complain Complain { get; set; }

        [ForeignKey("ComplainStatusID")]
        public virtual ComplainStatus ComplainStatus { get; set; }

        [ForeignKey("CreatedBy")]
        public virtual Users Users { get; set; }
    }
}

Introductory/Controllers/ComplainStatusController.cs
using Introductory.DAO;
using Introductory.Helper;
using Introductory.Models;
using Introductory.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Introductory.Controllers
{
    public class ComplainStatusController : BaseController
    {
        private readonly ApplicationDBContext _applicationDBContext;

        public ComplainStatusController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        [HttpPost]
        public JsonResult Save([FromBody] ComplainStatusVM vm)
        {
            if (string.IsNullOrEmpty(vm.ComplainStatusName))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Enter Complain Status Name"
                });
            }
            else if (string.IsNullOrEmpty(vm.ComplainStatusCode))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Select Complain Status Code"
                });
            }
            else
            {
                if (vm.ComplainStatusID == 0)
                {
                    // ADD NEW ROW
                    var oldComplain = _applicationDBContext
                                    .ComplainStatus
                                    .Where(x => x.ComplainStatusCode == vm.ComplainStatusCode)
                                    .FirstOrDefault();
                    if (oldComplain != null)
                    {
                        return Json(new
                        {
                            Success = false,
                            Message = "Complain Status Already Exists"
                        });
                    }
                    else
                    {
                        ComplainStatus dbMdl = new ComplainStatus()
                        {
                            ComplainStatusID = vm.ComplainStatusID,
                            ComplainStatusName = vm.ComplainStatusName.ToText(),
                            ComplainStatusCode = vm.ComplainStatusCode.ToText(),
                            CreatedDate = DateTime.Now,
                            CreatedBy = SignedInUserID,
                            IsActive = true,
                        };

                        _applicationDBContext.ComplainStatus.Add(dbMdl);

                        _applicationDBContext.SaveChanges();
                        return Json(new
                        {
                            Success = true,
                            Message = "Complain Status Registered Successfully!!!"
                        });
                    }
                }
                else
                {
                    // UPDATE EXISTING ROWS
                    var oldRow = _applicationDBContext.ComplainStatus
                                    .Where(x => x.ComplainStatusID == vm.ComplainStatusID)
                                    .FirstOrDefault();
                    if (oldRow == null)
                    {
                        return Json(new
                        {
                            Success = false,
                            Message = "Complain Status Not Found"
                        });
                    }
                    else
                    {
                        oldRow.ComplainStatusName = vm.ComplainStatusName.ToText();
                        oldRow.ComplainStatusCode = vm.ComplainStatusCode.ToText();

                        _applicationDBContext.SaveChanges();

                        return Json(new
                        {
                            Success = true,
                            Message = "Complain Status Updated Successfuly"
                        });
                    }
                }
            }
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            var oldData = _applicationDBContext
                            .ComplainStatus
                            .Where(x => x.ComplainStatusID == id)
                            .FirstOrDefault();

            if (oldData == null)
            {
                return Json(new
                {
                    Success = false,
                    Messaage = "Data Not Found!"
                });
            }
            else
            {
                oldData.IsActive = false;
                _applicationDBContext.SaveChanges();

                return Json(new
                {
                    Success = true,
                    Messaage = "Complain Status Deleted Successfully!"
                });
            }
        }

        [HttpPost]
        public JsonResult GetAllData([FromBody] ComplainStatusVM vm)
        {
            List<ComplainStatusVM> dbData = _applicationDBContext
                                            .ComplainStatus
                                            .Where(x =>
                                              x.IsActive == true
                                              && (string.IsNullOrEmpty(vm.ComplainStatusName) || x.ComplainStatusName.Contains(vm.ComplainStatusName))
                                              && (string.IsNullOrEmpty(vm.ComplainStatusCode) || x.ComplainStatusCode.Contains(vm.ComplainStatusCode))
                                            )
                                            .Select(s => new ComplainStatusVM
                                            {
                                                ComplainStatusID = s.ComplainStatusID.ToInt32(),
                                                ComplainStatusName = s.ComplainStatusName.ToText(),
                                                ComplainStatusCode = s.ComplainStatusCode.ToText(),
                                                //CreatedDate = s.CreatedDate.ToNepaliDate(), //if CreatedDate is string in modal
                                                CreatedDate = DateTime.Now.ToShortDateString(),
                                                //CreatedBy = LoggedInUserID,
                                                Created_By = s.Users.Username.ToText(),
                                            })
                                           .ToList();

            return Json(new
            {
                Success = true,
                Data = dbData
            });
        }

        [HttpGet]
        public JsonResult GetComplainStatus()
        {
            List <ComplainStatusVM> dbData = _applicationDBContext
                                          .ComplainStatus
                                          .Where(x => x.IsActive == true)
                                          .Select(s => new ComplainStatusVM
                                          {
                                              ComplainStatusID = s.ComplainStatusID.ToInt32(),
                                              ComplainStatusName = s.ComplainStatusName.ToText()
                                          })
                                          .ToList();

            return Json(new
            {
                Success = true,
                Data = dbData
            });
        }

        [HttpGet]
        public JsonResult GetComplainByID(int key)
        {
            var dbData = _applicationDBContext
                            .ComplainStatus
                            .Where(x => x.ComplainStatusID == key)
                            .FirstOrDefault();
            if (dbData == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Data Not Found In Database"
                });
            }
            else
            {
                return Json(new
                {
                    Success = true,
                    Data = dbData
                });
            }
        }
    }
}

Introductory/Controllers/ComplainStatusTrackInfoController.cs
using Introductory.DAO;
using Introductory.Helper;
using Introductory.Models;
using Introductory.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Introductory.Controllers
{
    public class ComplainStatusTrackInfoController : BaseController
    {
        ApplicationDBContext _applicationDBContext;

        public ComplainStatusTrackInfoController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetAllData([FromBody] ComplainStatusVM vm)
        {
            List<ComplainStatusTrackInfoVM> dbdata = _applicationDBContext
                                                     .ComplainStatusTrackInfo
                                                     .Where( x => 
                                                                (vm.ComplainStatusID == x.ComplainStatusID || vm.ComplainStatusID == 0)
                                                     )
                                                     .Select(x => new ComplainStatusTrackInfoVM
                                                     {
                                                         ComplainStatusTrackInfoID = x.ComplainStatusTrackInfoID.ToInt32(),
                                                         ComplainID = x.ComplainID.ToInt32(),
                                                         ComplainStatusID = x.ComplainStatusID.ToInt32(),
                                                         Remarks = x.Remarks.ToText(),
                                                         CreatedBy = x.CreatedBy.ToInt32(),
                                                         CreatedDate = x.CreatedDate.ToNepaliDate().ToText(),
                                                         Created_By = x.Users.Username.ToText(),
                                                         ComplainStatus = x.ComplainStatus.ComplainStatusName.ToText()
                                                     })
                                                     .ToList();

            return Json(new
            {
                Success = true,
                Data = dbdata
            });
        }
    }
}

Introductory/Views/ComplainStatusTrackInfo/Index.cshtml
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-md-4">
						<label class="col-form-label">Complain Status</label>
						<br />
						<select class="form-control ddlComplainStatus">
							
						</select>
					</div>
					<div class="col-md-4">
						<br />
						<button class="btn btn-secondary btnSearch mt-3"><i class="fa fa-search"></i> Search</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="row">
			<div class="card">
				<div class="card-body">
					<table class="table table-striped table-hover dtTable">
						<thead>
							<tr>
								<th>SN</th>
								<th>Complain Info ID</th>
								<th>Complain Status</th>
								<th>Remarks</th>
								<th>Created By</th>
								<th>Created Date</th>
							</tr>
						</thead>
						<tbody class="data-body  dtTableBody">

						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>


@section Scripts{
	<script>

		$(document).ready(function(){
			loadComplainStatusTrackInfo();
			loadComplainStatus();
		});

		$(document).on("click", ".btnSearch", function(){
			loadComplainStatusTrackInfo();
		});

		function loadComplainStatusTrackInfo(){

			var obj = {
				complainStatusID : $('.ddlComplainStatus').val() || '0'
			};

			$.ajax({
				method: 'post',
				contentType: "application/json; charset=utf-8",
				url: "@Url.Action("GetAllData","ComplainStatusTrackInfo")",
				data: JSON.stringify(obj),
				beforeSend: function(){
					$.blockUI()	
				},
				success: function(res){
					if(res.success){
						var data = res.data;

						var xyz = '';

						$.each(data, function(i, x){
							xyz += '<tr>';
							xyz += '<td>' + x.complainStatusTrackInfoID + '</td>';
							xyz += '<td>' + x.complainID + '</td>';
							xyz += '<td>' + x.complainStatus + '</td>';
							xyz += '<td>' + x.remarks + '</td>';
							xyz += '<td>' + x.created_By + '</td>';
							xyz += '<td>' + x.createdDate + '</td>';
							xyz += '</tr>';
						})

						$('.dtTableBody').html(xyz);

						$('.dtTable').DataTable();
						
					}
				},
				complete : function(){
					$.unblockUI();
				}
			})
		}

		function loadComplainStatus(){
			$.ajax({
				method: "get",
				contentType: "application/json; charset=utf-8",
				url: "@Url.Action("GetAllData", "ComplainStatus")",
				beforeSend: function(){
					$.blockUI();
				},
				success: function(res){

					if(res.success){

						var xyz = "<option value=0>---Select---</option>";

						var data = res.data;

						$.each(data, function(i, x){
							xyz += "<option value=" + x.complainStatusID + ">" + x.complainStatusName + "</option>";
						})

						$(".ddlComplainStatus").html(xyz);
					}

					debugger;
				},
				complete: function() {
					$.unblockUI();
				}
			})
		}

	</script>
}