Introductory/Controllers/ComplainTypeController.cs
using Introductory.DAO;
using Introductory.Models;
using Microsoft.AspNetCore.Mvc;

namespace Introductory.Controllers
{
    public class ComplainTypeController : BaseController
    {
        private readonly ApplicationDBContext _context;

        public ComplainTypeController(ApplicationDBContext applicationDBContext)
        {
            _context = applicationDBContext;
        }

        public IActionResult Index()
        {
            return View();
        }


        public JsonResult GetAllData(string name, string code)
        {


            var dbData = _context
                         .ComplainType
                         .Where(x =>
                                x.IsActive == true
                             && (string.IsNullOrEmpty(name) || x.ComplainTypeName.Contains(name))
                             && (string.IsNullOrEmpty(code) || x.ComplainTypeCode.Contains(code))
                         )
                         .OrderByDescending(o => o.CreatedDate)
                         .ToList();


            return Json(new
            {
                Success = true,
                Data = dbData
            });


        }
        public JsonResult GetComplainTypeByID(int key)
        {
            var dbData = _context
                            .ComplainType
                            .Where(x => x.ComplainTypeID == key)
                            .FirstOrDefault();
            if (dbData == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Data Not Found In Database"
                });
            }
            else
            {
                return Json(new
                {
                    Success = true,
                    Data = dbData
                });
            }
        }
        public JsonResult SaveData(int id, string name, string code)
        {
            if (string.IsNullOrEmpty(name))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Enter Compalin type Name"
                });
            }
            else if (string.IsNullOrEmpty(code))
            {
                return Json(new
                {
                    Success = false,
                    Message = "Enter Compalin type Code"
                });
            }
            else
            {
                if (id == 0)
                {
                    ComplainType CT;
                    CT = new ComplainType();

                    CT.ComplainTypeName = name;
                    CT.ComplainTypeCode = code;
                    CT.CreatedDate = DateTime.Now;
                    CT.CreatedBy = SignedInUserID;
                    CT.IsActive = true;


                    _context.ComplainType.Add(CT);
                    _context.SaveChanges();

                    var obj = new
                    {
                        Success = true,
                        Message = "Data Inserted Succesfully"
                    };
                    return Json(obj);
                }
                else
                {
                    // update garne
                    var dbData = _context
                                    .ComplainType
                                    .Where(x => x.ComplainTypeID == id)
                                    .FirstOrDefault();
                    if (dbData == null)
                    {
                        var obj = new
                        {
                            Success = false,
                            Message = "Data Not Found in Database"
                        };
                        return Json(obj);
                    }
                    else
                    {
                        dbData.ComplainTypeName = name;
                        dbData.ComplainTypeCode = code;

                        _context.SaveChanges();
                        var obj = new
                        {
                            Success = true,
                            Message = "Data Modified Successfully"
                        };
                        return Json(obj);
                    }
                }
            }

        }

        public JsonResult DeleteData(int key)
        {
            var dbData = _context
                            .ComplainType
                            .Where(x => x.ComplainTypeID == key)
                            .FirstOrDefault();
            if (dbData == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Data not found in Database"
                });
            }
            else
            {
                dbData.IsActive = false;
                _context.SaveChanges();

                return Json(new
                {
                    Success = true,
                    Message = "Complain Type Info Deleted Successfully"
                });
            }
        }
    }
}

Introductory/Controllers/UserGroupController.cs
 using Introductory.DAO;
using Introductory.Helper;
using Introductory.Models;
using Microsoft.AspNetCore.Mvc;

namespace Introductory.Controllers
{
    public class UserGroupController : BaseController
    {
        ApplicationDBContext _applicationDBContext;

        public UserGroupController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        public IActionResult Index()
        {
            //    List<UserGroup> ug = new List<UserGroup>
            //    {
            //        new UserGroup { Name = "Super Admin", Code = "SA", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Admin", Code = "AD", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Manager", Code = "MG", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Driver", Code = "DV", CreatedDate = DateTime.Now, isActive = 1 },
            //    };


            //    try   
            //    { 
            //    _applicationDBContext.UserGroup.AddRange(ug);
            //    _applicationDBContext.SaveChanges();
            //    }
            //    catch(Exception ex)
            //    {
            //        Console.WriteLine($"Error: { ex.Message }");
            //    }

            var data = _applicationDBContext.UserGroup.Where(x => x.isActive == 1).ToList();

            return View(data);
        }

        public JsonResult saveData(int id, string name, string code)
        {
            if (string.IsNullOrEmpty(name))
            {
                return Json(new
                {
                    success = false,
                    message = "Enter User group name"
                });
            }
            else if(string.IsNullOrEmpty(code))
            {
                return Json(new
                {
                    success = false,
                    message = "Enter user group code"
                });
            }
            else
            {
                var duplicate = _applicationDBContext
                                .UserGroup
                                .Where(x => x.Code == code)
                                .FirstOrDefault();

                if(duplicate == null)
                {
                    if(id == 0)
                    { 
                        UserGroup ug;
                        ug = new UserGroup()
                        {
                            Name = name,
                            Code = code,
                            CreatedDate = DateTime.Now,
                            CreatedBy = SignedInUserID,
                            isActive = 1
                        };

                        _applicationDBContext.Add(ug);
                        _applicationDBContext.SaveChanges();

                        var obj = new
                        {
                            success = true,
                            message = "Data added successfully"
                        };

                        return Json(obj);
                    }
                    else
                    {
                        //Update data
                        var dbData = _applicationDBContext
                                     .UserGroup
                                     .Where(x => x.UserGroupID == id)
                                     .FirstOrDefault();
                        if(dbData == null)
                        {
                            var obj = new
                            {
                                success = false,
                                message = "Data not found in Databse"
                            };

                            return Json(obj);
                        }
                        else
                        {
                            dbData.Name = name;
                            dbData.Code = code;

                            _applicationDBContext.SaveChanges();


                            var obj = new
                            {
                                success = true,
                                message = "Data updated successfully"
                            };

                            return Json(obj);
                        }
                    }
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "User group code already exists"
                    });
                }
            }
        }

        public JsonResult deleteData(int key)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => x.UserGroupID == key)
                        .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data not found"
                });
            }
            else
            {
                dbData.isActive = 0;
                _applicationDBContext.SaveChanges();
                return Json(new
                {
                    Success = true,
                    Message = "Data deleted successfully"
                });
            }
        }

        public JsonResult GetUserGroupByID(int key)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => x.UserGroupID == key)
                        .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data not found in Database"
                });
            }
            else
            {
                return Json(new
                {
                    success = true,
                    Data = dbData
                });
            }
        }

        public JsonResult GetAllData(string name, string code)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => 
                                x.isActive == 1
                                && (string.IsNullOrEmpty(name) || x.Name.Contains(name))
                                && (string.IsNullOrEmpty(code) || x.Code.Contains(code))
                                )
                        .OrderByDescending(o => o.CreatedDate)
                        .ToList();

            return Json(new
            {
                success = true,
                data = dbData
            });
        }
    }
}

Introductory/Views/ComplainType/Index.cshtml
<div class="row">
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body cust-bg">
						<div class="row">
							<div class="col-md-3">
								<label>Complain Type Name</label><br />
								<input type="text" class="form-control txtFilterName" />
							</div>
							<div class="col-md-3">
								<label>Complain Type Code</label><br />
								<input type="text" class="form-control txtFilterCode" />
							</div>
							<div class="col-md-3">
								<br />
								<button type="button" class="btn btn-primary btnSearch">
									<i class="fa fa-search"></i> SEARCH
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-12 mt-4">
				<div class="card">
					<div class="card-body">
						<table class="table table-hover table-striped dtTable">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Code</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody class="data-list">
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body cust-bg">
						<div class="row">
							<div class="col-md-11">Complain Type Name</div>
							<div class="col-md-11">
								<input type="text" class="form-control txtName" />
							</div>
						</div>
						<div class="row mt-2">
							<div class="col-md-11">Complain Type Code</div>
							<div class="col-md-11">
								<input type="text" class="form-control txtCode" />
							</div>
						</div>

						<div class="row mt-2">
							<div class="col-md-3"></div>
							<div class="col-md-9 text-right">
								<input type="hidden" class="hdnId" value="0" />
								<button type="button" class="btn btn-success" id="btnSave"><i class="fa fa-save"></i> SAVE</button>
								<button type="button" class="btn btn-danger" id="btnCancel"><i class="fa fa-refresh"></i> Cancel</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script>
         $(document).ready(function () {
                    loadData();
         })

         $(document).on("click", "#btnSave", function () {
             var name = $('.txtName').val();
             var code = $('.txtCode').val();
             var id = $('.hdnId').val();

             if (name == '') {
                 toastr["error"]("Enter Complain Type Name", "Error")
             } else if (code == '') {
                 toastr["error"]("Enter Complain Type Code", "Error")
             } else {

                 $.ajax({
                     method: 'get',
                     contentType: "application/json; charset=utf-8",
                     url: '@Url.Action("SaveData", "ComplainType")?id=' + id + '&name=' + name + '&code=' + code,
                     success: function (res) {
                         if (res.success == true) {
                             toastr["success"](res.message, "OK");
                             clearForm();
                             loadData();
                         } else {
                             toastr["error"](res.message, "ERROR")
                         }
                     },
                     error: function (err) {
                         debugger;
                     },
                     beforeSend: function () {
                         $.blockUI();
                     },
                     complete: function () {
                         $.unblockUI();
                     }
                 });

             }
         })

         $(document).on('click', '#btnCancel', function () {
             var result = confirm("Are you sure to clear data?");
             if (result == true) {
                 clearForm();
             }
         })

         function clearForm() {
             $('.txtName').val("")
             $('.txtCode').val("")
             $('.hdnId').val(0)
         }

         $(document).on('click', '.btnDelete', function () {
             var id = $(this).data('key');
             var result = confirm('Are you sure to delete data?');
             if (result == true) {
                 $.ajax({
                     method: 'get',
                     contentType: "application/json; charset=utf-8",
                     url: '@Url.Action("DeleteData", "ComplainType")?key=' + id,
                     success: function (res) {
                         if (res.success == true) {
                             toastr["success"](res.message, "OK");
                             loadData();
                         } else {
                             toastr["error"](res.message, "ERROR")
                         }
                     },
                     error: function (err) {
                         debugger;
                     },
                     beforeSend: function () {
                         $.blockUI();
                     },
                     complete: function () {
                         $.unblockUI();
                     }
                 })
             }
         })

         $(document).on('click', '.btnEdit', function () {
             var id = $(this).data('key');

             $.ajax({
                 method: 'get',
                 contentType: "application/json; charset=utf-8",
                 url: '@Url.Action("GetComplainTypeByID", "ComplainType")?key=' + id,
                 success: function (res) {
                     if (res.success == true) {
                         $('.txtName').val(res.data.complainTypeName);
                         $('.txtCode').val(res.data.complainTypeCode);

                         $('.hdnId').val(res.data.complainTypeId);
                     } else {
                         toastr["error"](res.message, "ERROR")
                     }
                 },
                 error: function (err) {
                     debugger;
                 },
                 beforeSend: function () {
                     $.blockUI();
                 },
                 complete: function () {
                     $.unblockUI();
                 }
             })

         });


         function loadData() {
             var name = $('.txtFilterName').val();
             var code = $('.txtFilterCode').val();

             $.ajax({
                 method: 'get',
                 contentType: "application/json; charset=utf-8",
                 url: '@Url.Action("GetAllData", "ComplainType")?name=' + name + '&code=' + code,
                 success: function (res) {
                     if (res.success == true) {
                         var dbData = res.data;


                         var xyz = '';
                         $.each(dbData, function (i, x) {
                             xyz += '<tr>';
                             xyz += '<td>' + x.complainTypeID + '</td>';
                             xyz += '<td>' + x.complainTypeName + '</td>';
                             xyz += '<td>' + x.complainTypeCode + '</td>';
                             xyz += '<td><button type="button" class="btn btn-warning btn-sm mr-2 btnEdit" data-key="' + x.complainTypeId + '"><i class="fa fa-edit"></i> Edit</buttion><button type="button" class="btn btn-danger btn-sm btnDelete" data-key="' + x.complainTypeId + '"><i class="fa fa-trash"></i> Delete</buttion></td>'
                             xyz += '</tr>';
                         });

                         $('.data-list').html(xyz);

                         $('.dtTable').DataTable();

                     } else {
                         toastr["error"](res.message, "ERROR")
                     }
                 },
                 error: function (err) {
                     debugger;
                 },
                 beforeSend: function () {
                     $.blockUI();
                 },
                 complete: function () {
                     $.unblockUI();
                 }
             })
         }

         $(document).on('click', '.btnSearch', function () {
             loadData();
         });

         $(document).on("click", ".btnView", function () {
             var id = $(this).data('key');
             $.ajax({
                 method: 'get',
                 contentType: "application/json; charset=utf-8",
                 url: '@Url.Action("GetUserGroupByID", "UserGroup")?key=' + id,
                 success: function (res) {
                     if (res.success == true) {
                         alert(res.data.createdDate);
                     } else {
                         toastr["error"](res.message, "ERROR")
                     }
                 },
                 error: function (err) {
                     debugger;
                 },
                 beforeSend: function () {
                     $.blockUI();
                 },
                 complete: function () {
                     $.unblockUI();
                 }
             })


         });

	</script>
}