Introductory/Models/Users.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Introductory.Models
{
    public class Users
    {
        [Key]
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserGroupId { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public DateTime? DOB { get; set; }

        public bool isActive { get; set; }

        [ForeignKey("UserGroupId")]
        public virtual UserGroup UserGroup { get; set; }
    }
}

Introductory/Controllers/UserGroupController.cs
 using Introductory.DAO;
using Introductory.Helper;
using Introductory.Models;
using Microsoft.AspNetCore.Mvc;

namespace Introductory.Controllers
{
    public class UserGroupController : BaseController
    {
        ApplicationDBContext _applicationDBContext;

        public UserGroupController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        public IActionResult Index()
        {
            //    List<UserGroup> ug = new List<UserGroup>
            //    {
            //        new UserGroup { Name = "Super Admin", Code = "SA", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Admin", Code = "AD", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Manager", Code = "MG", CreatedDate = DateTime.Now, isActive = 1 },
            //        new UserGroup { Name = "Driver", Code = "DV", CreatedDate = DateTime.Now, isActive = 1 },
            //    };


            //    try   
            //    { 
            //    _applicationDBContext.UserGroup.AddRange(ug);
            //    _applicationDBContext.SaveChanges();
            //    }
            //    catch(Exception ex)
            //    {
            //        Console.WriteLine($"Error: { ex.Message }");
            //    }

            var data = _applicationDBContext.UserGroup.Where(x => x.isActive == 1).ToList();

            return View(data);
        }

        public JsonResult saveData(int id, string name, string code)
        {
            if (string.IsNullOrEmpty(name))
            {
                return Json(new
                {
                    success = false,
                    message = "Enter User group name"
                });
            }
            else if(string.IsNullOrEmpty(code))
            {
                return Json(new
                {
                    success = false,
                    message = "Enter user group code"
                });
            }
            else
            {
                var duplicate = _applicationDBContext
                                .UserGroup
                                .Where(x => x.Code == code)
                                .FirstOrDefault();

                if(duplicate == null)
                {
                    if(id == 0)
                    { 
                        UserGroup ug;
                        ug = new UserGroup()
                        {
                            Name = name,
                            Code = code,
                            CreatedDate = DateTime.Now,
                            CreatedBy = SignedInUserID,
                            isActive = 1
                        };

                        _applicationDBContext.Add(ug);
                        _applicationDBContext.SaveChanges();

                        var obj = new
                        {
                            success = true,
                            message = "Data added successfully"
                        };

                        return Json(obj);
                    }
                    else
                    {
                        //Update data
                        var dbData = _applicationDBContext
                                     .UserGroup
                                     .Where(x => x.UserGroupID == id)
                                     .FirstOrDefault();
                        if(dbData == null)
                        {
                            var obj = new
                            {
                                success = false,
                                message = "Data not found in Databse"
                            };

                            return Json(obj);
                        }
                        else
                        {
                            dbData.Name = name;
                            dbData.Code = code;

                            _applicationDBContext.SaveChanges();


                            var obj = new
                            {
                                success = true,
                                message = "Data updated successfully"
                            };

                            return Json(obj);
                        }
                    }
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "User group code already exists"
                    });
                }
            }
        }

        public JsonResult deleteData(int key)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => x.UserGroupID == key)
                        .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data not found"
                });
            }
            else
            {
                dbData.isActive = 0;
                _applicationDBContext.SaveChanges();
                return Json(new
                {
                    Success = true,
                    Message = "Data deleted successfully"
                });
            }
        }

        public JsonResult GetUserGroupByID(int key)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => x.UserGroupID == key)
                        .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data not found in Database"
                });
            }
            else
            {
                return Json(new
                {
                    success = true,
                    Data = dbData
                });
            }
        }

        public JsonResult GetAllData(string name, string code)
        {
            var dbData = _applicationDBContext
                        .UserGroup
                        .Where(x => 
                                x.isActive == 1
                                && (string.IsNullOrEmpty(name) || x.Name.Contains(name))
                                && (string.IsNullOrEmpty(code) || x.Code.Contains(code))
                                )
                        .OrderByDescending(o => o.CreatedDate)
                        .ToList();

            return Json(new
            {
                success = true,
                data = dbData
            });
        }
    }
}

Introductory/Controllers/UsersController.cs
using System.ComponentModel.DataAnnotations;
using System.Net;
using Introductory.DAO;
using Introductory.Helper;
using Introductory.Models;
using Introductory.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Introductory.Controllers
{
    public class UsersController : BaseController
    {
        ApplicationDBContext _applicationDBContext;

        public UsersController(ApplicationDBContext applicationDBContext)
        {
            _applicationDBContext = applicationDBContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save([FromBody] UsersVM usersVM)
        {

            if (string.IsNullOrEmpty(usersVM.UserName))
            {
                var obj = new
                {
                    Success = false,
                    Message = "Username is required"
                };

                return Json(obj);
            }
            else if(usersVM.UserGroupId == 0)
            {
                var obj = new
                {
                    Success = false,
                    Message = "UserGroup ID required"
                };

                return Json(obj);
            }
            else if(usersVM.Password != usersVM.ConfirmPassword)
            {
                var obj = new
                {
                    Success = false,
                    Message = "Confirm your password."
                };

                return Json(obj);
            }
            else if (string.IsNullOrEmpty(usersVM.Password))
            {
                var obj = new
                {
                    Success = false,
                    Message = "Password is required"
                };

                return Json(obj);
            }
            else if(string.IsNullOrEmpty(usersVM.ConfirmPassword))
            {
                var obj = new
                {
                    Success = false,
                    Message = "Confirm your password"
                };

                return Json(obj);
            }
            else if(string.IsNullOrEmpty(usersVM.Fullname))
            {
                var obj = new 
                { 
                    Success = false,
                    Message = "Fullname is required"
                };

                return Json(obj);
            }
            else if(string.IsNullOrEmpty(usersVM.Email))
            {
                var obj = new
                {
                    Success = false,
                    Message = "Email is required"
                };

                return Json(obj);
            }
            else if(string.IsNullOrEmpty(usersVM.ContactNo))
            {
                var obj = new
                {
                    Success = false,
                    Message = "Contact number is required"
                };

                return Json(obj);
            }
            else
            {
                var duplicate = _applicationDBContext
                                 .Users
                                 .Where(x => x.Username == usersVM.UserName)
                                 .FirstOrDefault();
                
                if(duplicate == null)
                {
                    if(usersVM.UserID == 0)
                    { 
                        Users newUser = new Users()
                        {
                            Username = usersVM.UserName,
                            UserGroupId = usersVM.UserGroupId,
                            Password = usersVM.Password,
                            ValidFrom = usersVM.ValidFrom.ToEnglishDate(),
                            ValidTo = usersVM.ValidTo.ToEnglishDate(),
                            Fullname = usersVM.Fullname,
                            Email = usersVM.Email,
                            ContactNo = usersVM.ContactNo,
                            Address = usersVM.Address,
                            DOB = usersVM.DOB.ToEnglishDate(),
                            isActive = true
                        };

                        _applicationDBContext.Add(newUser);
                        _applicationDBContext.SaveChanges();

                        var obj = new
                        {
                            Success = true,
                            Message = "User added successfully"
                        };

                        return Json(obj);
                    }
                    else
                    {
                        //Update data

                        var oldData = _applicationDBContext
                                        .Users
                                        .Where(x => x.UserID == usersVM.UserID)
                                        .FirstOrDefault();

                        if(oldData == null)
                        {
                            return Json(new
                            {
                                Success = false,
                                Message = "User not found in database"
                            });
                        }
                        else
                        {
                            oldData.Username = usersVM.UserName;
                            oldData.UserGroupId = usersVM.UserGroupId;
                            oldData.Password = usersVM.Password;
                            oldData.ValidFrom = usersVM.ValidFrom.ToEnglishDate();
                            oldData.ValidTo = usersVM.ValidTo.ToEnglishDate();
                            oldData.Fullname = usersVM.Fullname;
                            oldData.Email = usersVM.Email;
                            oldData.ContactNo = usersVM.ContactNo;
                            oldData.Address = usersVM.Address;
                            oldData.DOB = usersVM.DOB.ToEnglishDate();

                            _applicationDBContext.SaveChanges();

                            return Json(new
                            {
                                Success = true,
                                Message = "User updated successfully."
                            });
                            

                        }

                    }
                }
                else
                {
                    return Json(new
                    {
                        success = false,
                        message = "User already exists"
                    });
                }
                
            }
        }


        [HttpPost]
        public JsonResult GetAllData([FromBody] UsersVM usersVM)
        {
            List<UsersVM> dbData = _applicationDBContext
                                .Users
                                .Where(x => x.isActive == true
                                     &&(string.IsNullOrEmpty(usersVM.UserName) || x.Username.Contains(usersVM.UserName))
                                     &&(string.IsNullOrEmpty(usersVM.ContactNo) || x.Username.Contains(usersVM.ContactNo))
                                )
                                .Select(x => new UsersVM
                                {
                                    UserID = x.UserID.ToInt32(),
                                    UserName = x.Username.ToText(),
                                    Fullname = x.Fullname.ToText(),
                                    Address = x.Address.ToText(),
                                    Email = x.Email.ToText(),
                                    ContactNo = x.ContactNo.ToText(),
                                    ValidFrom = x.ValidFrom.ToNepaliDate(),
                                    ValidTo = x.ValidTo.ToNepaliDate()
                                })
                                .ToList();

            return Json(new
            {
                success = true,
                data = dbData
            });
        }

        public JsonResult GetUserById(int id)
        {
            UsersVM? dbData = _applicationDBContext
                           .Users
                           .Where(x => x.UserID == id)
                           .Select(x => new UsersVM
                           {
                               UserName = x.Username.ToText(),
                               Fullname = x.Fullname.ToText(),
                               Address = x.Address.ToText(),
                               Email = x.Email.ToText(),
                               ContactNo = x.ContactNo.ToText(),
                               ValidFrom = x.ValidFrom.ToNepaliDate().ToText(),
                               ValidTo = x.ValidTo.ToNepaliDate().ToText(),
                               DOB = x.DOB.ToNepaliDate().ToText()
                           })
                           .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Data not found in database"
                });
            }
            else
            {
                return Json(new
                {
                    Success = true,
                    data = dbData
                });
            }


        }

        public JsonResult deleteData(int id)
        {
            var dbData = _applicationDBContext
                            .Users
                            .Where(x => x.UserID == id)
                            .FirstOrDefault();

            if(dbData == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data does not exist in database"
                });
            }
            else
            {
                dbData.isActive = false;
                _applicationDBContext.SaveChanges();
                return Json(new
                {
                    success = true,
                    message = "Data deleted successfully"

Introductory/Views/Users/Index.cshtml
<div class="row mt-2">
	<div class="col-md-12">
		<div class="card p-3 mb-2 bg-light text-dark">
			<div class="card-body p-3 mb-2 bg-light text-dark">
				<div class="row">
					<div class="col-md-3">
						<label>UserName</label>
						<br />
						<input type="text" class="form-control txtFilterUsername"/>
					</div>

					<div class="col-md-3">
						<label>ContactNo</label>
						<br />
						<input type="text" class="form-control txtFilterContactNo" />
					</div>

					<div class="col-md-3">
						<br />
						<button type="button" class="btn btn-secondary btnSearch"><i class="fa fa-search"></i> Search</button>
						<button type="button" class="btn btn-success btnNew"><i class="fa fa-plus"></i> New</button>
					</div>
				
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row mt-2">
	<div class="col-md-12">
		<div class="card">
			<div class="card-body">
				<table class="table table-striped table-hover dataTable">
					<thead>
						<tr>
							<th>SN</th>
							<th>UserName</th>
							<th>FullName</th>
							<th>Email</th>
							<th>ContactNo</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody class="data-list"></tbody>	
				</table>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="mdlSetup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-xl" role="document">
		<div class="modal-content text-bg-light p-3">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">User Form</h5>
				<button type="button" class="close fa fa-close" id="modalCollapse" data-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-6">
						<div class="card text-bg-info bg-opacity-50">
							<div class="card-body text-bg-info bg-opacity-50">
								<div class="row">
									<div class="col-md-4">
										UserName
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtUsername" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										User Group
									</div>
									<div class="col-md-8">
										<select class="form-control ddlUsergroup">
											
										</select>
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Password
									</div>
									<div class="col-md-8">
										<input type="password" class="form-control  txtPassword" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Confirm Password
									</div>
									<div class="col-md-8">
										<input type="password" class="form-control txtConfirmpw" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Valid From
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtValidfrom nepdate-picker" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Valid To
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtValidto nepdate-picker" />
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="card text-bg-info bg-opacity-50">
							<div class="card-body text-bg-info bg-opacity-50">
								<div class="row">
									<div class="col-md-4">
										FullName
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtFullname" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Email
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtEmail" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										Address
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtAddress" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										ContactNo
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtContact" />
									</div>
								</div>
								<div class="row mt-2">
									<div class="col-md-4">
										DOB
									</div>
									<div class="col-md-8">
										<input type="text" class="form-control txtDOB nepdate-picker" />
									</div>
								</div>
							</div>
						  </div>
					   </div>
				    </div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary fa fa-refresh btnCancel" data-dismiss="modal"> Cancel</button>
					<button type="button" class="btn btn-primary fa fa-floppy-o btnSave"> Save</button>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	<script>
		$(document).ready(function(){
			loadUserGroup();
			loadData();
			$('.ddlUsergroup').select2({
				dropdownParent: $('#mdlSetup')
			});
			$('.dataTable').DataTable();
		});

		$(document).on('click','.btnNew', function(){
			$('#mdlSetup').modal('show')
		})

		$(document).on('click', '#modalCollapse', function(){
			$('#mdlSetup').modal('hide')
		})

		function clearForm(){
			$('.txtUsername').val('')
			$('.ddlUsergroupname').val('')
			$('.txtPassword').val('')
			$('.txtConfirmpw').val('')
			$('.txtValidto').val('')
			$('.txtValidfrom').val('')
			$('.txtFullname').val('')
			$('.txtEmail').val('')
			$('.txtAddress').val('')
			$('.txtContact').val('')
			$('.txtDOB').val('')
		}

		$(document).on('click','.btnCancel', function(){
			var userResponse = confirm("Are you sure you want to cancel?")
			if(userResponse){
				clearForm()
			}
		})

		$(document).on('click', '.btnSave', function(){
			var obj = {
				userID: $('.btnEdit').data("key"), 
				userName: $('.txtUsername').val() || "",
				UserGroupId: $('.ddlUsergroup').val() || 0,
				Password: $('.txtPassword').val() || "",
				ConfirmPassword: $('.txtConfirmpw').val() || "",
				ValidFrom: $('.txtValidfrom').val() || "",
				ValidTo: $('.txtValidto').val() || "",
				Fullname: $('.txtFullname').val() || "",
				Email: $('.txtEmail').val() || "",
				ContactNo: $('.txtContact').val() || "",
				Address: $('.txtAddress').val() || "",
				DOB: $('.txtDOB').val() || ""
			}
			debugger;

			if(obj.userName == ''){
				 $(".txtUsername").focus()
					toastr["error"]("Enter Valid User Name", "Error")
			}
			else if(obj.Password == ''){
					$(".txtPassword").focus()
					toastr["error"]("Enter Valid password", "Error")
			}
			else if(obj.ConfirmPassword == ''){
					$(".txtConfirmpw").focus()
					toastr["error"]("Please confirm your password", "Error")
			}	
			else if(obj.Fullname == ''){
				$(".txtFullname").focus()
					toastr["error"]("Enter Valid Full name", "Error")
			}
			else if(obj.ContactNo == ''){
					$(".txtContact").focus()
					toastr["error"]("Enter Valid Contact Number","Error")
			}
			else
			{
				$.ajax({
					method:'post',
					contentType: "application/json; charset=utf-8",
					url: '@Url.Action("Save", "Users")',
					data: JSON.stringify(obj),
					beforeSend: function () {
						$.blockUI();
					},
					success: function(res){
						if(res.success){
							$('#mdlSetup').modal('hide')
							toastr["success"]("User Added successfully", "success")
							clearForm();
							$('#mdlSetup').modal('hide')
							loadData()
						}
						else
						{
							toastr["error"](res.message, "Error")
							clearForm();

						}
					},
					complete:function(){
						$.unblockUI()
					},
					error: function (err) {
						console.log(err);
						alert('Error Occured!!')
					}
				})
			}
		})

		$(document).on('click', '.btnEdit', function(){

			var id = $(this).data("key");
			debugger;

			$.ajax({
				method: 'get',
				contentType: 'application/json; charset=utf-8',
				url: '@Url.Action("GetUserById","Users")?id=' + id,
				success: function(res){
					if(res.success)
					{
						$('#mdlSetup').modal('show')

						$('.txtUsername').val(res.data.userName)
						$('.ddlUsergroupname').val(res.data.userGroupId)
						$('.txtValidto').val(res.data.validTo)
						$('.txtValidfrom').val(res.data.validFrom)
						$('.txtFullname').val(res.data.fullname)
						$('.txtEmail').val(res.data.email)
						$('.txtAddress').val(res.data.address)
						$('.txtContact').val(res.data.contactNo)
						$('.txtDOB').val(res.data.dob)
					}
				},
				error: function(){

				},
				beforeSend: function(){
					$.blockUI();
				},
				complete: function(){
					$.unblockUI();
				}
			})
			

		})

		function loadUserGroup(){
			$.ajax({
				method: 'get',
				contentType: 'application/json; charset=utf-8',
				url: '@Url.Action("GetAllData","UserGroup")',
				success: function(res){
					if(res.success){
						var data = res.data;

						var xyz = '<option>--Select--</option>';

						$.each(data,function(i,x){
							xyz += '<option value=' + x.userGroupID + '>' + x.name + '</option>'
						});

						$('.ddlUsergroup').html(xyz);
					}
				}
			})
		}

		$(document).on('click','.btnSearch', function(){
			loadData();
		})

		function loadData(){

			var obj = {
				userName : $('.txtFilterUsername').val() || '' ,
				contactNo : $('.txtFilterContactNo').val() || ''
			};

			$.ajax({
				method: 'post',
				contentType: 'application/json; charset=utf-8',
				url: '@Url.Action("GetAllData", "Users")',
				data: JSON.stringify(obj),
				success: function(res){
					if(res.success){
						var dbData = res.data
					
						var xyz = ''

						$.each(dbData, function(i, x){
							xyz +=  '<tr>'
							xyz +=  '<td>' + x.userID + '</td>';
							xyz +=  '<td>' + x.userName + '</td>';
							xyz +=  '<td>' + x.fullname + '</td>';
							xyz +=  '<td>' + x.email + '</td>';
							xyz +=  '<td>' + x.contactNo + '</td>';
							xyz +=  '<td><button type="button" class="btn btn-warning sm btnEdit me-2" data-key="' + x.userID + '"><i class="fa fa-edit"></i> Edit</button><button type="button" class="btn btn-danger btnDelete" data-key="' + x.userID + '"><i class="fa fa-trash"></i> Delete</button></td>'
							xyz +=  '</tr>';
						})

						$('.data-list').html(xyz)
					}
					else {
						toastr["error"](res.message, "ERROR")
					}
				}
			})
		}

		$(document).on('click', '.btnDelete', function(){

			 var id = $(this).data('key');

			 Swal.fire({
			 title: "Are you sure?",
			 text: "You won't be able to revert this!",
			 icon: "warning",
			 showCancelButton: true,
			 confirmButtonColor: "#3085d6",
			 confirmButtonText: "Yes, delete it!",
			 cancelButtonColor: "#d33",
			 }).then((result) => {
			 if (result.isConfirmed) {
				  $.ajax({
					 method: 'get',
					 contentType: 'application/json;charset=utf-8',
					 url: '@Url.Action("deleteData", "Users")?id=' + id,
					 beforeSend: function(){$.blockUI()},
					 success: function(res){
						 if(res.success == true){
							 Swal.fire({
							   title: "Deleted!",
							   text: "User has been deleted.",
							   icon: "success"
								 });
							 loadData();
						 }
						 else
						 {
							 Swal.fire({
							 icon: "error",
							 title: "Oops...",
							 text: "User Not Found",
							 footer: '<a href="#">Why do I have this issue?</a>'
							 });
						 }
					 },
					 complete: function(){$.unblockUI()},
					 error: function(err){

					 }
				 })
			   }
			 });
		})
	</script>
}